centreon:
    resource: "./Centreon/**/*.yaml"
    prefix: "/{base_uri}api/{version}"
    defaults:
        base_uri: "centreon/"
        version: "v21.10"
    requirements:
        base_uri: "(.+/)|.{0}"
